Improve script and README
vplasencia/bandada-sdk-demo pull request #1
Opened 2024-01-25 14:41 UTC by 0xjei

This PR use `figlet`, `chalk` and `node-emoji` packages to style the script. Then, a up-to-date README version is provided.

2024-01-30 18:46 UTC, vplasencia requested changes
Everything looks great! Very beautiful 🤩

Thanks for the great work 🔥

I just left one comment.

2024-01-30 18:46 UTC, vplasencia commented on src/bandada-sdk.ts
> +const log = console.log
```suggestion
const { log } = console
```

There was an ESLint error that can be fixed with this.

2024-01-30 18:48 UTC, vplasencia commented
Which version of yarn are you using? I'm getting a different `yarn.lock` file.

2024-01-31 13:14 UTC, 0xjei commented
> Which version of yarn are you using? I'm getting a different `yarn.lock` file.

The repository did not specify which version to use, so my system defaulted to the legacy version 1.22.19. I will update it now! Thank you

2024-01-31 13:24 UTC, 0xjei commented
@vplasencia updated to latest yarn stable version (4.1.0)

2024-01-31 15:49 UTC, vplasencia commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-4.1.0.cjs
We don't have this folder in the project. I think we can create it or just leave the version in the package.json file.

2024-02-01 10:46 UTC, vplasencia approved these changes

2024-02-01 10:46 UTC, merged