Docs: Readme
vplasencia/bandada-sdk-demo pull request #10
Opened 2024-10-30 11:54 UTC by sashaphmn

The previous link did not work

2024-10-30 11:59 UTC, vplasencia requested changes
Hey @sashaphmn! Thank you very much. I left one comment with the correct link to get the API key.

2024-10-30 11:59 UTC, vplasencia commented on README.md
> +You just need to activate your API key via the [Bandada Dashboard](https://bandada.pse.dev/) homepage. Then you need to copy & paste the key into the `ADMIN_API_KEY` environment variable.
```suggestion
You just need to activate your API key via the [Bandada Dashboard](https://app.bandada.pse.dev/) homepage. Then you need to copy & paste the key into the `ADMIN_API_KEY` environment variable.
```

2024-10-30 16:10 UTC, sashaphmn commented
Hey. Always happy to help

2024-10-30 17:35 UTC, vplasencia commented
Hey @sashaphmn could you update the PR with this link `https://app.bandada.pse.dev/` instead of `https://app.bandada.pse.dev/`?

2024-10-31 10:17 UTC, sashaphmn commented
Done

2024-10-31 10:19 UTC, vplasencia approved these changes
Hey @sashaphmn! Looks great! Thank you very much 🙏

2024-10-31 10:19 UTC, merged